In [3]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv('../../data/corporate-purchase/corporate-purchase.csv')

In [19]:
df1 = pd.read_csv('./data/corporate-purchase/corporate-purchase-log.csv')

# An√°lise corporate-purchase

In [13]:
df.shape

(15881, 9)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15881 entries, 0 to 15880
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    15881 non-null  int64
 1   status                15881 non-null  object
 2   created               15881 non-null  object
 3   cardId                15881 non-null  int64
 4   holderId              15881 non-null  int64
 5   amount                15881 non-null  int64
 6   merchantName          15865 non-null  object
 7   merchantCategoryType  14356 non-null  object
 8   workspaceId           15881 non-null  int64
dtypes: int64(5), object(4)
memory usage: 1.1+ MB

In [15]:
df.describe()

                 id        cardId      holderId        amount   workspaceId
count  1.588100e+04  1.588100e+04  1.588100e+04  1.588100e+04  1.588100e+04
mean   5.651614e+15  5.683628e+15  5.688071e+15  7.778848e+06  5.700810e+15
std    6.117832e+14  5.037466e+14  4.522814e+14  7.935632e+08  3.622503e+14
min    4.503716e+15  4.503720e+15  4.504839e+15 -1.309656e+07  4.800539e+15
25%    5.144993e+15  5.376672e+15  5.652130e+15  0.000000e+00  5.506711e+15
50%    5.686562e+15  5.682955e+15  5.686543e+15  6.666000e+03  5.506711e+15
75%    6.146463e+15  6.099623e+15  5.818010e+15  1.925915e+06  5.983985e+15
max    6.755125e+15  6.755245e+15  6.753841e+15  1.000000e+11  6.301997e+15

In [16]:
df.head()

,id,status,created,cardId,holderId,amount,merchantName,merchantCategoryType,workspaceId
0,6526920292302848,denied,2024-08-19 19:23:25.684853 UTC,6120924482895872,6436057776128000,600,RB EMPREENDIMENTOS TUR,hotels,5506710584164352
1,5181209059524608,denied,2024-08-19 19:09:36.706781 UTC,6120924482895872,6436057776128000,600,RB EMPREENDIMENTOS TUR,hotels,5506710584164352
2,6044901582045184,denied,2024-08-19 19:06:07.294333 UTC,6120924482895872,6436057776128000,600,RB EMPREENDIMENTOS TUR,hotels,5506710584164352
3,6223425823571968,denied,2024-08-19 19:02:49.960943 UTC,6120924482895872,6436057776128000,600,RB EMPREENDIMENTOS TUR,hotels,5506710584164352
4,5251577803702272,denied,2024-08-19 18:59:02.361198 UTC,6120924482895872,6436057776128000,600,RB EMPREENDIMENTOS TUR,hotels,5506710584164352

In [18]:
# Convert `created` column to datetime
df['created'] = pd.to_datetime(df['created'], format="%Y-%m-%d %H:%M:%S.%f UTC")

# Summary statistics for numeric columns
print("\nSummary Statistics for Numeric Columns:\n")
print(df.describe().to_markdown(numalign="left", stralign="left"))

# Value counts for categorical columns
categorical_cols = ['status', 'merchantName', 'merchantCategoryType']

for col in categorical_cols:
    print(f"\nValue Counts for {col}:\n")
    print(df[col].value_counts().reset_index().rename(columns={'index':col, col:'count'}).to_markdown(index=False, numalign="left", stralign="left"))

Summary Statistics for Numeric Columns:

|       | id          | created                       | cardId      | holderId    | amount       | workspaceId   |
|:------|:------------|:------------------------------|:------------|:------------|:-------------|:--------------|
| count | 15881       | 15881                         | 15881       | 15881       | 15881        | 15881         |
| mean  | 5.65161e+15 | 2023-04-29 01:13:14.577472768 | 5.68363e+15 | 5.68807e+15 | 7.77885e+06  | 5.70081e+15   |
| min   | 4.50372e+15 | 2021-10-15 22:14:13.843645    | 4.50372e+15 | 4.50484e+15 | -1.30966e+07 | 4.80054e+15   |
| 25%   | 5.14499e+15 | 2023-02-08 15:22:33.957054976 | 5.37667e+15 | 5.65213e+15 | 0            | 5.50671e+15   |
| 50%   | 5.68656e+15 | 2023-06-01 20:26:30.449441024 | 5.68296e+15 | 5.68654e+15 | 6666         | 5.50671e+15   |
| 75%   | 6.14646e+15 | 2023-06-10 18:14:59.005243904 | 6.09962e+15 | 5.81801e+15 | 1.92592e+06  | 5.98399e+15   |
| max   | 6.75512e+15 | 2024-08-19 19:23:25.684853    | 6.75524e+15 | 6.75384e+15 | 1e+11        | 6.302e+15     |
| std   | 6.11783e+14 | nan                           | 5.03747e+14 | 4.52281e+14 | 7.93563e+08  | 3.6225e+14    |

Value Counts for status:

| count     | count   |
|:----------|:--------|
| confirmed | 6912    |
| denied    | 4900    |
| canceled  | 3488    |
| voided    | 456     |
| approved  | 125     |

Value Counts for merchantName:

| count                          | count   |
|:-------------------------------|:--------|
| 99 TAXI                        | 4849    |
| GOOGLE                         | 4401    |
| GOOGLE CLOUD PLATFORM          | 1016    |
| AMAZON                         | 889     |
| IFOOD                          | 726     |
| FACEBOOK                       | 419     |
| UBER                           | 305     |
| GOOOGLE                        | 284     |
| BARATA VOADORA                 | 202     |
| GCP                            | 188     |
| STARLINK                       | 187     |
| WWW.HEROKUCHARGE.COM           | 114     |
| Misc Retail                    | 74      |
| MUG.SP                         | 64      |
| COMPANY 123                    | 52      |
| SARAIVA                        | 51      |
| SEGUNDO TESTE                  | 47      |
| AWS                            | 42      |
| PAYPAL                         | 41      |
| COMERCIO 123                   | 40      |
| IFOOD * COMIDA                 | 37      |
| MERCHANT CHIQUE                | 34      |
| AXSON GROUP                    | 34      |
| TESTE SALDO DOIDO              | 34      |
| CVR INC.                       | 33      |
| KERRY LTDA.                    | 33      |
| REGRAS DOIDAS                  | 31      |
| NEGATIVA A√ç                    | 30      |
| NETFLIX TEMPORARIO             | 30      |
| NOME DO MERCHANT               | 27      |
| VBAFT GROUP                    | 27      |
| RAIO X                         | 25      |
| PARCELADO                      | 25      |
| ILEGALIDADES                   | 23      |
| COMIDA NICE                    | 23      |
| ROBERCI THE BARD               | 21      |
| TESTE SCORE                    | 19      |
| DANDO RUIM MAS BOM             | 19      |
| TTFEI LTDA.                    | 18      |
| AMPM                           | 16      |
| SENHOR INCRIVEL ZUADAO         | 16      |
| CARRO ELETRICO VRUMVRU         | 16      |
| TESTE MCC                      | 16      |
| APROVAIVOS                     | 14      |
| DELSIN THE MERCH               | 13      |
| ONF * ONIB * 044820            | 13      |
| COMIDAAAO                      | 13      |
| MUG.SP DA MUGA                 | 13      |
| Service Station                | 13      |
| MASSARU O VENDEDOR             | 13      |
| TAXIS ON BOOKING               | 12      |
| DEBUG                          | 12      |
| L√ìGUI                          | 11      |
| FANTA SEA                      | 11      |
| PAG * INGRESSE                 | 10      |
| Department Store               | 10      |
| Automated Cash Disb            | 10      |
| PET NICE DEMAIS                | 9       |
| Manual Cash Disburs            | 9       |
| TESTE PATCH                    | 9       |
| Computer Software              | 9       |
| ORDEM DOIDA                    | 8       |
| MAMASSU                        | 8       |
| THE FIRST ONE                  | 8       |
| POR FAVOR 8                    | 7       |
| MANUAL CASH DISBURS            | 7       |
| FIGMA                          | 7       |
| IS TRY P                       | 7       |
| BRUNEIJI MERCADOR              | 7       |
| EGMRP Inc.                     | 6       |
| RB EMPREENDIMENTOS TUR         | 6       |
| KFQBG Group                    | 6       |
| Jerome Castilo 13867031681     | 6       |
| SALINA EI                      | 6       |
| Clifford EI                    | 6       |
| Raphael Ltda.                  | 6       |
| XBOL Ltda.                     | 6       |
| GWY Ltda.                      | 6       |
| Obdulia Inc.                   | 6       |
| DVTBX Inc.                     | 6       |
| WENDY EI                       | 6       |
| Tommie Inc.                    | 6       |
| Harlan Inc.                    | 6       |
| Jerrica Inc.                   | 6       |
| MUG DA MUGA                    | 6       |
| KKVYZ Ltda.                    | 6       |
| Shayne EI                      | 6       |
| CATEGORYTYPE                   | 5       |
| DEPARTMENT STORE               | 5       |
| Merchant Payment               | 5       |
| TEST SEMI FINAL 9              | 4       |
| HPIN S.A.                      | 4       |
| GOOOGLE 555                    | 4       |
| Lodging                        | 4       |
| AUSTRALIAN BOAT COMPAN         | 4       |
| EMPRESA SHOW                   | 4       |
| DOTTORI NO CINEMA 1            | 4       |
| NETFLIX CHIQUE                 | 4       |
| GOOOGLE 488                    | 4       |
| Eating Place                   | 4       |
| BBV INC.                       | 3       |
| GOOOGLE 241                    | 3       |
| ROBERCI THE BARD 19 MA         | 3       |
| TEST 34 NOELLA CITY BR         | 3       |
| FAIJSGBIASBGIABSG              | 3       |
| GOOOGLE 124                    | 3       |
| TEST 5                         | 3       |
| GOOOGLE 843                    | 3       |
| TIO PATINHAS 2 TIANA C         | 3       |
| HKP S.A.                       | 3       |
| TEST 34                        | 3       |
| GOOOGLE 845                    | 3       |
| PT E EN                        | 3       |
| TEST 2                         | 2       |
| TIO PATINHAS 5                 | 2       |
| TEST SEMI FINAL 12             | 2       |
| TEST SEMI FINAL 10             | 2       |
| GOOOGLE 110                    | 2       |
| GOOOGLE 384                    | 2       |
| TEST SEMI FINAL 5              | 2       |
| GOOOGLE 126                    | 2       |
| GOOOGLE 833                    | 2       |
| TEST 1                         | 2       |
| TIPO SPOTIFY                   | 2       |
| GOOOGLE 977                    | 2       |
| GOOOGLE 119                    | 2       |
| GOOOGLE 560                    | 2       |
| TEST 27                        | 2       |
| GOOOGLE 141                    | 2       |
| GOOOGLE 723                    | 2       |
| GOOOGLE 624                    | 2       |
| GOOOGLE 835                    | 2       |
| GOOOGLE 793                    | 2       |
| TEST 16                        | 2       |
| GOOOGLE 874                    | 2       |
| TEST 2 TOOZE CITY BRA          | 2       |
| NWGX INC.                      | 2       |
| TEST 30                        | 2       |
| GOOOGLE 343                    | 2       |
| NICE PURCHASE 3 MAIS C         | 2       |
| GOOOGLE 307                    | 2       |
| GOOOGLE 188                    | 2       |
| TEST 29                        | 2       |
| TEST 99 DWIGHT CITY BR         | 2       |
| ROBERCI THE BARD 7             | 2       |
| CANCELANTE                     | 2       |
| GOOOGLE 220                    | 2       |
| POR FAVOR 3 CHESNUT CI         | 2       |
| BATATA 1 TERRANCE CITY         | 2       |
| POR FAVOR 2                    | 2       |
| GOOOGLE 986                    | 2       |
| GOOOGLE 203                    | 2       |
| ROBERCI THE BARD 10            | 2       |
| GOOOGLE 766                    | 2       |
| TEST 19                        | 2       |
| GOOOGLE 245                    | 2       |
| KRIS EIRELI                    | 2       |
| GOOOGLE 650                    | 2       |
| GOOOGLE 565                    | 2       |
| GOOOGLE 639                    | 2       |
| GOOOGLE 23                     | 2       |
| GOOOGLE 370                    | 2       |
| GOOOGLE 570                    | 2       |
| GOOOGLE 292                    | 2       |
| GOOOGLE 980                    | 2       |
| GOOOGLE 705                    | 2       |
| GOOOGLE 230                    | 2       |
| GOOOGLE 99                     | 2       |
| GOOOGLE 783                    | 2       |
| GOOOGLE 919                    | 2       |
| GOOOGLE 472                    | 2       |
| GOOOGLE 388                    | 2       |
| GOOOGLE 192                    | 2       |
| GOOOGLE 731                    | 2       |
| Fuel Dispenser                 | 2       |
| GOOOGLE 826                    | 2       |
| GOOOGLE 451                    | 2       |
| Direct Marketing Merc          | 2       |
| GOOOGLE 984                    | 1       |
| GOOOGLE 694                    | 1       |
| LHKAS Inc.                     | 1       |
| GOOOGLE 886                    | 1       |
| GOOOGLE 113                    | 1       |
| GOOOGLE 557                    | 1       |
| GOOOGLE 899                    | 1       |
| GOOOGLE 229                    | 1       |
| Tuan Eireli                    | 1       |
| GOOOGLE 329                    | 1       |
| GOOOGLE 930                    | 1       |
| GOOOGLE 988                    | 1       |
| GOOOGLE 895                    | 1       |
| Verena Ltda.                   | 1       |
| GOOOGLE 219                    | 1       |
| Leroy EI                       | 1       |
| GOOOGLE 413                    | 1       |
| GOOOGLE 772                    | 1       |
| Wes Inc.                       | 1       |
| GOOOGLE 434                    | 1       |
| GOOOGLE 585                    | 1       |
| GOOOGLE 732                    | 1       |
| GOOOGLE 638                    | 1       |
| GOOOGLE 28                     | 1       |
| GOOOGLE 367                    | 1       |
| GOOOGLE 283                    | 1       |
| GOOOGLE 853                    | 1       |
| GOOOGLE 9                      | 1       |
| GOOOGLE 326                    | 1       |
| GOOOGLE 973                    | 1       |
| GOOOGLE 958                    | 1       |
| GOOOGLE 11                     | 1       |
| GOOOGLE 830                    | 1       |
| BEOF Group                     | 1       |
| GOOOGLE 510                    | 1       |
| Casey Banome 96883584447       | 1       |
| ERES LEDGERZADO                | 1       |
| GOOOGLE 333                    | 1       |
| GOOOGLE 579                    | 1       |
| GOOOGLE 549                    | 1       |
| GOOOGLE 844                    | 1       |
| YIFHE Inc.                     | 1       |
| GOOOGLE 387                    | 1       |
| GOOOGLE 64                     | 1       |
| GOOOGLE 531                    | 1       |
| GOOOGLE 758                    | 1       |
| UPQQ INC.                      | 1       |
| Tawana Ltda.                   | 1       |
| GOOOGLE 541                    | 1       |
| GOOOGLE 365                    | 1       |
| GOOOGLE 334                    | 1       |
| GOOOGLE 856                    | 1       |
| GOOOGLE 660                    | 1       |
| GOOOGLE 685                    | 1       |
| GOOOGLE 440                    | 1       |
| GOOOGLE 94                     | 1       |
| GOOOGLE 882                    | 1       |
| GOOOGLE 850                    | 1       |
| GOOOGLE 573                    | 1       |
| GOOOGLE 72                     | 1       |
| GOOOGLE 803                    | 1       |
| GOOOGLE 78                     | 1       |
| GOOOGLE 636                    | 1       |
| GOOOGLE 290                    | 1       |
| Dillon Inc.                    | 1       |
| GOOOGLE 752                    | 1       |
| GOOOGLE 891                    | 1       |
| GOOOGLE 373                    | 1       |
| GOOOGLE 911                    | 1       |
| GOOOGLE 589                    | 1       |
| GOOOGLE 525                    | 1       |
| GOOOGLE 501                    | 1       |
| GOOOGLE 372                    | 1       |
| GOOOGLE 516                    | 1       |
| GOOOGLE 940                    | 1       |
| GOOOGLE 700                    | 1       |
| GOOOGLE 183                    | 1       |
| GOOOGLE 432                    | 1       |
| GOOOGLE 10                     | 1       |
| GOOOGLE 513                    | 1       |
| GOOOGLE 657                    | 1       |
| GOOOGLE 202                    | 1       |
| GOOOGLE 618                    | 1       |
| GOOOGLE 675                    | 1       |
| GOOOGLE 456                    | 1       |
| GOOOGLE 693                    | 1       |
| GOOOGLE 149                    | 1       |
| GOOOGLE 79                     | 1       |
| GOOOGLE 486                    | 1       |
| GOOOGLE 738                    | 1       |
| GOOOGLE 864                    | 1       |
| GOOOGLE 664                    | 1       |
| GOOOGLE 83                     | 1       |
| GOOOGLE 661                    | 1       |
| GOOOGLE 673                    | 1       |
| GOOOGLE 123                    | 1       |
| GOOOGLE 621                    | 1       |
| GOOOGLE 378                    | 1       |
| GOOOGLE 635                    | 1       |
| GOOOGLE 233                    | 1       |
| GOOOGLE 107                    | 1       |
| GOOOGLE 574                    | 1       |
| GOOOGLE 364                    | 1       |
| GOOOGLE 51                     | 1       |
| GOOOGLE 210                    | 1       |
| GOOOGLE 806                    | 1       |
| GOOOGLE 848                    | 1       |
| GOOOGLE 131                    | 1       |
| GOOOGLE 978                    | 1       |
| GOOOGLE 463                    | 1       |
| GOOOGLE 854                    | 1       |
| GOOOGLE 174                    | 1       |
| GOOOGLE 289                    | 1       |
| GOOOGLE 632                    | 1       |
| GOOOGLE 769                    | 1       |
| GOOOGLE 429                    | 1       |
| NICE PURCHASE 1                | 1       |
| BISABFIASBFBASIGBIASG          | 1       |
| JRR Group                      | 1       |
| WMRA S.A.                      | 1       |
| JIW Ltda.                      | 1       |
| KNL Ltda.                      | 1       |
| Kim Ltda.                      | 1       |
| GGUDH Inc.                     | 1       |
| Dave Evanko 38887959315        | 1       |
| NWGX Inc.                      | 1       |
| Kris Eireli                    | 1       |
| FQEU Inc.                      | 1       |
| LWV Group                      | 1       |
| Abe Ltda.                      | 1       |
| Donetta EI                     | 1       |
| PEVJK Group                    | 1       |
| UYE Ltda.                      | 1       |
| TGCDL Ltda.                    | 1       |
| IODH Group                     | 1       |
| Nicki Eireli                   | 1       |
| YDKKO Inc.                     | 1       |
| XEG Group                      | 1       |
| JQVWX Inc.                     | 1       |
| PFF Group                      | 1       |
| Willy Inc.                     | 1       |
| Young Inc.                     | 1       |
| TEST 23                        | 1       |
| TEST 22                        | 1       |
| TEST 21                        | 1       |
| TEST 20                        | 1       |
| TEST 18                        | 1       |
| TEST 17                        | 1       |
| TEST 15                        | 1       |
| TEST 14                        | 1       |
| TEST 13                        | 1       |
| TEST 12                        | 1       |
| TEST 11                        | 1       |
| TEST 10                        | 1       |
| TEST 9                         | 1       |
| TEST 8                         | 1       |
| TEST 7                         | 1       |
| TEST 6                         | 1       |
| TEST 4                         | 1       |
| TEST 3                         | 1       |
| Daron Hemmerling 85912085368   | 1       |
| George Fronk 61977028438       | 1       |
| Alec Eireli                    | 1       |
| Mayme Eireli                   | 1       |
| AJQW Group                     | 1       |
| Kali Eireli                    | 1       |
| Terrell Ltda.                  | 1       |
| Jame EI                        | 1       |
| Kendall Balko 86157207116      | 1       |
| Leandro EI                     | 1       |
| Cornell Ltda.                  | 1       |
| Ernesto Ltda.                  | 1       |
| Caitlyn Gruninger 32628274523  | 1       |
| Errol Eireli                   | 1       |
| OQS Inc.                       | 1       |
| Janell Eireli                  | 1       |
| Melonie Inc.                   | 1       |
| Chris Ltda.                    | 1       |
| AECS Group                     | 1       |
| Kacie Brisley 47104089209      | 1       |
| BIG SAD                        | 1       |
| VBAFT Group                    | 1       |
| RIGQ Inc.                      | 1       |
| QHIR S.A.                      | 1       |
| UPQQ Inc.                      | 1       |
| Hailey Eireli                  | 1       |
| EZURV S.A.                     | 1       |
| Lacey Fennewald 93839152429    | 1       |
| GCX Ltda.                      | 1       |
| Kermit Ltda.                   | 1       |
| Jeffry Ltda.                   | 1       |
| QKHTW Inc.                     | 1       |
| Sara Ltda.                     | 1       |
| RIOF S.A.                      | 1       |
| Joseph Berl 20259148229        | 1       |
| Shelby Eireli                  | 1       |
| GQXD S.A.                      | 1       |
| WMD Group                      | 1       |
| Wm Eireli                      | 1       |
| UMCOQ Group                    | 1       |
| Kalyn Eireli                   | 1       |
| YHIJ Group                     | 1       |
| PYIL Inc.                      | 1       |
| OITNY Inc.                     | 1       |
| SSDFN S.A.                     | 1       |
| KSV Ltda.                      | 1       |
| Vashti Inc.                    | 1       |
| TEST 23 MILLY CITY BRA         | 1       |
| TEST 24                        | 1       |
| TEST 25                        | 1       |
| YGRU S.A.                      | 1       |
| Julio Ltda.                    | 1       |
| PEYY Ltda.                     | 1       |
| CACHORRO NICE                  | 1       |
| JANELL EIRELI                  | 1       |
| NICE PURCHASE 5 XAVIER         | 1       |
| NICE PURCHASE 4                | 1       |
| NICE PURCHASE 2                | 1       |
| GOOOGLE 13                     | 1       |
| PO FAVORE 11 RODARTA C         | 1       |
| PLEASE 10 BLA                  | 1       |
| POR FAVOR 9                    | 1       |
| POR FAVOR 6                    | 1       |
| POR FAVOR 5                    | 1       |
| POR FAVOR 3 GETTO CITY         | 1       |
| POR FAVOR 3                    | 1       |
| ROBERCI THE BARD 16 OL         | 1       |
| POR FAVOR 1                    | 1       |
| BATATA 2                       | 1       |
| BATATA 1                       | 1       |
| Guadalupe Inc.                 | 1       |
| Viviana Inc.                   | 1       |

### Exporta√ß√£o do caso de demo

In [32]:
df_filtrado = df[df['holderId'] == '5,66363E+15']

path = '../../data/corporate-purchase/demo_corporate_purchase.csv'
df_filtrado.to_csv(path, index=False)

# An√°lise corporate-purchase-log

In [26]:
df1.shape

(32284, 12)

In [27]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32284 entries, 0 to 32283
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             32284 non-null  int64
 1   created                        32284 non-null  object
 2   purchase_cardId                32284 non-null  int64
 3   purchase_id                    32284 non-null  int64
 4   purchase_status                32280 non-null  object
 5   purchase_created               32219 non-null  object
 6   purchase_cardId_1              32284 non-null  int64
 7   purchase_holderId              32284 non-null  int64
 8   purchase_amount                32284 non-null  int64
 9   purchase_merchantName          32260 non-null  object
 10  purchase_merchantCategoryType  28048 non-null  object
 11  purchase_workspaceId           32284 non-null  int64
dtypes: int64(7), object(5)
memory usage: 3.0+ MB

In [28]:
df1.describe()

,id,purchase_cardId,purchase_id,purchase_cardId_1,purchase_holderId,purchase_amount,purchase_workspaceId
count,3.228400e+04,3.228400e+04,3.228400e+04,3.228400e+04,3.228400e+04,3.228400e+04,3.228400e+04
mean,5.593664e+15,5.688882e+15,5.655836e+15,5.688882e+15,5.690865e+15,4.369276e+06,5.744113e+15
std,6.387869e+14,5.420226e+14,6.126253e+14,5.420226e+14,4.959359e+14,5.566943e+08,3.649348e+14
min,4.503741e+15,4.503720e+15,4.503716e+15,4.503720e+15,4.504839e+15,-1.200000e+04,4.800539e+15
25%,5.024776e+15,5.325523e+15,5.145708e+15,5.325523e+15,5.478125e+15,1.000000e+03,5.506711e+15
50%,5.608920e+15,5.682955e+15,5.693748e+15,5.682955e+15,5.686543e+15,3.333000e+03,5.983985e+15
75%,6.127957e+15,6.158986e+15,6.146116e+15,6.158986e+15,5.932404e+15,1.234423e+06,5.983985e+15
max,6.755355e+15,6.755245e+15,6.755125e+15,6.755245e+15,6.753841e+15,1.000000e+11,6.301997e+15

In [29]:
df1.head()

,id,created,purchase_cardId,purchase_id,purchase_status,purchase_created,purchase_cardId_1,purchase_holderId,purchase_amount,purchase_merchantName,purchase_merchantCategoryType,purchase_workspaceId
0,5507146275880960,2024-08-28 06:41:18.369572 UTC,4647528301592576,5957105974509568,canceled,2024-05-29 17:09:07.532413 UTC,4647528301592576,5405946780057600,0,PARCELADO,services,5506710584164352
1,5977757854990336,2024-08-28 06:41:16.176039 UTC,5325522896683008,6471832572002304,canceled,2024-05-29 15:00:24.674018 UTC,5325522896683008,5723947190452224,0,FACEBOOK,hotels,6301997028343808
2,4698580195475456,2024-08-28 06:41:15.769302 UTC,4647528301592576,6255450911670272,canceled,2024-05-29 17:02:54.573873 UTC,4647528301592576,5405946780057600,0,PARCELADO,services,5506710584164352
3,5623488014450688,2024-08-28 06:41:13.059499 UTC,4647528301592576,4890915575431168,canceled,2024-05-29 17:07:41.359761 UTC,4647528301592576,5405946780057600,0,PARCELADO,services,5506710584164352
4,5702717007724544,2024-08-28 06:40:21.021123 UTC,5650928946380800,6615052886999040,canceled,2024-05-29 15:00:23.561805 UTC,5650928946380800,5663631916138496,0,GOOGLE CLOUD PLATFORM,services,4800539376222208